name: pre-commit

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
        - uses: elastic/oblt-actions/pre-commit@v1

        - name: Set up Git auth for private pre-commit hooks
          run: |
            git config --global url."https://${{ secrets.PRECOMMIT_TEST }}:x-oauth-basic@github.com/".insteadOf "https://github.com/"

