name: pre-commit

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: elastic/infosec-precommit/pre-commit@v1.0.1